### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [arielpollack/PinCodeView#6]
Good day @arielpollack  I am a graphic designer and i would like to contribute to your nice project by designing a logo for it if you will pemit me. Thanks and best regards! 

-Tobaloidee

**Comment by arielpollack** [comment]
Sounds awesome @Tobaloidee :)

**Comment by Tobaloidee** [comment]
Thanks for the positive feedback @arielpollack  :+1: 

will start my design now and show it here when done..

**Comment by Tobaloidee** [comment]
here's my design Sir, still open for suggestions..

I made a minimal design of a pincode boxes..made the first box red for added uniqueness

![pres-01](https://user-images.githubusercontent.com/36028424/42353860-cddf509c-80f5-11e8-86b5-62c75b259b08.png)
